#!/bin/bash

: '
Light - Backlight manager
Written by Darth Venom and Tobi Emotic
< = >
'

if [ -z $EUID ]; then
	EUID=0;
fi
if [[ -n "$1" && ! "$1" == "-" && ! "$1" == "--" ]]
then

	if [ "$1" == "--max" ]
	then
		cat /sys/class/backlight/intel_backlight/max_brightness;
	elif [ "$1" == "-m" ]
	then
		cat /sys/class/backlight/intel_backlight/max_brightness;

	elif [ "$1" == "--act" ]
	then
		cat /sys/class/backlight/intel_backlight/actual_brightness;
	
	elif [ "$1" == "-a" ]
	then
		cat /sys/class/backlight/intel_backlight/actual_brightness;

	elif [ "$1" == "--set" ]
	then
		if [ $EUID -ne 0 ]
		then
			echo -e "\033[1;32mRun as root (sudo)\033[0m";
		else
			if [ -z "$2" ]; then
				printf "\t\033[1;31mMissing argum\033[0m\n";
			else
				echo -n $2 >> /sys/class/backlight/intel_backlight/brightness;
			fi
		fi
	
	elif [ "$1" == "-s" ]
	then
		if [ $EUID -ne 0 ]
		then
			echo -e "\033[1;32mRun as root (sudo)\033[0m";
		else
			if [ -z "$2" ]; then
				printf "\t\033[1;31mMissing argument\033[0m\n";
			else
				echo -n $2 >> /sys/class/backlight/intel_backlight/brightness;
			fi
		fi
	
	elif [ "$1" == "-i" ]
	then
		if [ $EUID -ne 0 ];
		then
			printf "\033[1;32mRun as root (sudo)\033[0m\n";
		else
			bri=`cat /sys/class/backlight/intel_backlight/actual_brightness`
			bri=`expr $bri + 50`
			echo $bri >> /sys/class/backlight/intel_backlight/brightness;
		fi

	elif [ "$1" == "--help" ]
	then
		echo light - Controls Backlight;
		echo;
		echo Usage: light -m
		echo Usage: light -a
		echo Usage: light -s [Value]
		echo Usage: light -i
		echo
		echo
		echo Options:
		echo " -m, --max			Displays max value for brightness"
		echo " -a, --act			Displays current brightness value"
		echo " -s, --set			Sets backlight value"
		echo " -i				Increases backlight value +50"

	else
		echo "unknown option '$1'"
	fi

else
	echo "light: missing operand"
	echo "Try 'light --help'"
fi
